#! /usr/bin/ev sh

#@ Copyright (C) 2018, Ryan E. McClue <ryan.e.mcclue@gmail.com>

#@ Rlinter: 
#@	"GNU indent wrapper script employing many of the guidelines
#@	stated in Ryan's C Style Guide."
#@	(GNU indent): https://www.gnu.org/software/indent/
#@	(Ryan's C Style Guide):  https://github.com/users/OutbackMan

#@ LICENSE:
#@ "This file is subject to the terms and conditions defined in
#@ 'LICENSE.md', which is part of this source code package."

readonly PROJECT_DIRECTORY="${1}"

readonly GENERAL_PARAMS="--ignore-profile --no-verbosity"

readonly FORMAT_PARAMS="--blank-lines-after-declarations --brace-indent0 "\
		"--break-before-boolean-operator --continuation-indent4 "\
		"--indent-level4 --line-length80 --no-space-after-casts "\
		"--swallow-optional-blank-lines --tab-size4"

readonly FUNCTION_PARAMS="--blank-lines-after-procedures "\
		"--braces-after-func-def-line --continue-at-parentheses "\
		"--dont-break-procedure-type --no-space-after-function-call-names "\
		"--no-space-after-parentheses"

readonly CONDITIONAL_PARAMS="--braces-after-if-line --cuddle-else "\
		"--else-endif-column33 --space-after-if"

readonly STRUCT_UNION_PARAMS="--braces-on-struct-decl-line --struct-brace-indentation0"

readonly CASE_PARAMS="--case-indentation0 --indent-label0"

readonly COMMENT_PARAMS="--comment-delimiters-on-blank-lines "\
		"--comment-indentation33 --declaration-comment-column33 "\
		"--dont-star-comments"

readonly LOOP_PARAMS="--cuddle-do-while --space-after-for --space-after-while"

readonly MACRO_PARAMS="--preprocessor-indentation0"

readonly PARAMS="${GENERAL_PARAMS} ${FORMAT_PARAMS} ${FUNCTION_PARAMS} "\
		"${CONDITIONAL_PARAMS} ${STRUCT_UNION_PARAMS} ${CASE_PARAMS} "\
		"${COMMENT_PARAMS} ${LOOP_PARAMS} ${MACRO_PARAMS}"

readonly FILES=$(find "${PROJECT_DIRECTORY}" -type f -name '*.c' -o -name '*.h')

for file in "${FILES}"; do
	indent "${PARAMS}"
done
